name: mirabelle
favicon: null
layout_spectrum: 1
typography_spectrum: 0.69944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#b1b2b7'
    - '#070506'
    - '#65605d'
    - '#9e2200'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
